site_name: Pods & Clues™
site_description: A narrative-driven Kubernetes training series set inside Zentari Labs
site_url: https://www.podsandclues.com

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/homepage/logo.jpg
  favicon: assets/homepage/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: teal
  font:
    text: Inter
    code: JetBrains Mono

extra_css:
  - css/extra.css

extra_javascript:
  - js/feedback-scroll.js

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets

plugins:
  - macros
  - search
  - autorefs
  - minify:
      minify_html: true


