site_name: Pods and Clues
site_description: A narrative-driven Kubernetes training series set inside Zentari Labs
site_url: https://www.podsandclues.com

theme:
  name: material
  logo: assets/homepage/logo.png
  favicon: assets/homepage/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: teal
  font:
    text: Inter
    code: JetBrains Mono

nav:
  - Home: index.md
  - Training Modules: training-modules/
  - Cases:
    - Case 000 - The Curious Ones: cases/case-000.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/typeit@8.7.1/dist/index.umd.min.js
  - scripts/typing-block.js

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets

plugins:
  - search
  - autorefs
  - minify:
      minify_html: true


